In [1]:
import numpy as np

In [2]:
def process_data(fileName):
    """
        处理训练数据，得到词典及词频
    """
    fi = open(fileName)
    data = fi.readlines()
    voc = dict() # word: index
    for sentence in data:
        for word in sentence.split():
            voc[word] = len(voc)
#             voc[word] = voc.get(word, 0) + 1
    print("词典大小V={}".format(len(voc)))

    return voc


In [3]:
voc = process_data('data.txt')

词典大小V=57


In [25]:
# Hyper parameters
num_epoches = 10
learning_rate = 1e-3
embed_size = 50

In [76]:
def train(fileName):
    fi = open(fileName)
    data = fi.readlines()
    train_data = [] # training dataset
    voc = dict() # word: index
    for sentence in data:
        words = sentence.split()
        for word in words:
            if word not in voc:
                voc[word] = len(voc)
        contexts = [voc[word] for word in words]
        targets = contexts[1:]
        
        instances = zip(contexts, targets)
        train_data.extend(instances)
        
    for key, value in voc.iteritems():
        print(key, value)

    W_ih = np.random.rand(len(voc), embed_size) # input-> hidden
    W_ho = np.random.rand(embed_size, len(voc)) # hidden-> output
    
    for epoch in range(num_epoches):
        np.random.shuffle(train_data)
        for (context, target) in train_data:
            h = W_ih[context]
            print(h.shape)
            
            
            
            
        
            

In [77]:
train('data.txt')

('and', 31)
('vectors', 47)
('another', 56)
('produces', 32)
('being', 44)
('text', 30)
('is', 1)
('positioned', 48)
('related', 5)
('one', 55)
('assigned', 45)
('located', 52)
('as', 25)
('are', 8)
('trained', 19)
('in', 42)
('close', 53)
('embeddings', 13)
('networks', 18)
('group', 3)
('takes', 24)
('space', 34)
('its', 26)
('to', 10)
('linguistic', 21)
('corpus', 29)
('several', 36)
('proximity', 54)
('These', 14)
('such', 49)
('used', 9)
('word2vec', 0)
('that', 7)
('models', 6)
('share', 50)
('shallow', 15)
('produce', 11)
('words', 23)
('input', 27)
('corresponding', 46)
('reconstruct', 20)
('unique', 41)
('with', 39)
('dimensions', 38)
('a', 2)
('hundred', 37)
('word', 12)
('neural', 17)
('contexts', 22)
('of', 4)
('two-layer', 16)
('large', 28)
('vector', 33)
('common', 51)
('each', 40)
('the', 43)
('typically', 35)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(50,)
(

In [75]:
W = np.random.rand(10, 3)

In [34]:
W

array([[ 0.06803076,  0.39383774,  0.85585632],
       [ 0.51859607,  0.48140407,  0.50598491],
       [ 0.79030476,  0.27472857,  0.43963816],
       [ 0.32093847,  0.38517586,  0.08607958],
       [ 0.89215937,  0.49011104,  0.10645915],
       [ 0.54295043,  0.95387362,  0.26826965],
       [ 0.67076356,  0.25250385,  0.61592096],
       [ 0.72278961,  0.63333196,  0.52754134],
       [ 0.6515762 ,  0.29903175,  0.57174803],
       [ 0.02024718,  0.0398519 ,  0.23493161]])

In [78]:
x = np.random.rand(30)

In [79]:
x.shape

(30,)

In [82]:
y = x.T

In [83]:
y.shape

(30,)

In [84]:
x

array([ 0.23212075,  0.08074165,  0.88657083,  0.05463195,  0.92863822,
        0.91607245,  0.54261173,  0.10846951,  0.99991672,  0.65470099,
        0.82615975,  0.6861992 ,  0.70642702,  0.93524781,  0.38856278,
        0.98615319,  0.11828926,  0.5871078 ,  0.15426504,  0.33687733,
        0.85452707,  0.7878448 ,  0.71027733,  0.85835364,  0.81330451,
        0.51805601,  0.51636949,  0.04849647,  0.13577178,  0.40603766])

In [85]:
y

array([ 0.23212075,  0.08074165,  0.88657083,  0.05463195,  0.92863822,
        0.91607245,  0.54261173,  0.10846951,  0.99991672,  0.65470099,
        0.82615975,  0.6861992 ,  0.70642702,  0.93524781,  0.38856278,
        0.98615319,  0.11828926,  0.5871078 ,  0.15426504,  0.33687733,
        0.85452707,  0.7878448 ,  0.71027733,  0.85835364,  0.81330451,
        0.51805601,  0.51636949,  0.04849647,  0.13577178,  0.40603766])

In [89]:
np.dot(x.T, y.T)

12.406514336272176

array([ 0.05388004,  0.00651921,  0.78600784,  0.00298465,  0.86236895,
        0.83918874,  0.29442749,  0.01176564,  0.99983345,  0.42863339,
        0.68253993,  0.47086934,  0.49903914,  0.87468846,  0.15098103,
        0.97249812,  0.01399235,  0.34469557,  0.0237977 ,  0.11348634,
        0.73021651,  0.62069943,  0.50449388,  0.73677097,  0.66146423,
        0.26838202,  0.26663745,  0.00235191,  0.01843398,  0.16486658])