In [1]:
import numpy as np

In [2]:
# def process_data(fileName):
#     """
#         处理训练数据，得到词典及词频
#     """
#     fi = open(fileName)
#     data = fi.readlines()
#     voc = dict() # word: index
#     for sentence in data:
#         for word in sentence.split():
#             voc[word] = len(voc)
# #             voc[word] = voc.get(word, 0) + 1
#     print("词典大小V={}".format(len(voc)))

#     return voc


In [3]:
# voc = process_data('data.txt')

In [4]:
# Hyper parameters
num_epoches = 10
learning_rate = 1e-3
embed_size = 50

In [43]:
def softmax(v):
    exp_v = np.exp(v)
    return exp_v/np.sum(exp_v)

In [46]:
a = np.random.rand(3)

In [47]:
a

array([ 0.53122263,  0.43240865,  0.49959187])

np.max(a)

In [48]:
np.max(a)

0.53122262663312514

In [42]:
def train(fileName):
    fi = open(fileName)
    data = fi.readlines()
    train_data = [] # training dataset
    voc = dict() # word: index
    for sentence in data:
        words = sentence.split()
        for word in words:
            if word not in voc:
                voc[word] = len(voc)
        contexts = [voc[word] for word in words]
        targets = contexts[1:]
        
        instances = zip(contexts, targets)
        train_data.extend(instances)
        
    for key, value in voc.iteritems():
        print(key, value)

    W_ih = np.random.rand(len(voc), embed_size) # input-> hidden
    W_ho = np.random.rand(embed_size, len(voc)) # hidden-> output
    
    for epoch in range(num_epoches):
        np.random.shuffle(train_data)
        for (context, target) in train_data:
            h = W_ih[context].reshape(embed_size, 1) # (emb_size, 1)
            u = np.dot(W_ho.T, h) # (V, 1)
            
            
            
            print(u.shape)
            
            
            
            
        
            

In [41]:
train('data.txt')

('and', 31)
('vectors', 47)
('another', 56)
('produces', 32)
('being', 44)
('text', 30)
('is', 1)
('positioned', 48)
('related', 5)
('one', 55)
('assigned', 45)
('located', 52)
('as', 25)
('are', 8)
('trained', 19)
('in', 42)
('close', 53)
('embeddings', 13)
('networks', 18)
('group', 3)
('takes', 24)
('space', 34)
('its', 26)
('to', 10)
('linguistic', 21)
('corpus', 29)
('several', 36)
('proximity', 54)
('These', 14)
('such', 49)
('used', 9)
('word2vec', 0)
('that', 7)
('models', 6)
('share', 50)
('shallow', 15)
('produce', 11)
('words', 23)
('input', 27)
('corresponding', 46)
('reconstruct', 20)
('unique', 41)
('with', 39)
('dimensions', 38)
('a', 2)
('hundred', 37)
('word', 12)
('neural', 17)
('contexts', 22)
('of', 4)
('two-layer', 16)
('large', 28)
('vector', 33)
('common', 51)
('each', 40)
('the', 43)
('typically', 35)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57, 1)
(57

In [10]:
W = np.random.rand(10, 3)

In [11]:
W

array([[ 0.46652307,  0.75851841,  0.59031115],
       [ 0.41653274,  0.1648482 ,  0.27187295],
       [ 0.91226603,  0.80216151,  0.99406523],
       [ 0.75175497,  0.35526154,  0.20035416],
       [ 0.66342557,  0.05718345,  0.43687913],
       [ 0.67794988,  0.52239992,  0.8318094 ],
       [ 0.48944587,  0.33079543,  0.52421869],
       [ 0.1297268 ,  0.71665949,  0.53202965],
       [ 0.63572923,  0.09915536,  0.6903671 ],
       [ 0.06669984,  0.14426   ,  0.27801081]])

In [12]:
x = np.random.rand(30)

In [13]:
x.shape

(30,)

In [14]:
y = x.T

In [15]:
y.shape

(30,)

In [16]:
x

array([ 0.65295049,  0.92489308,  0.01254219,  0.10456262,  0.08021775,
        0.83164729,  0.32037566,  0.63287415,  0.60054947,  0.3719682 ,
        0.93099506,  0.01004934,  0.6230401 ,  0.91938009,  0.50833923,
        0.74486386,  0.13728699,  0.11399029,  0.17540258,  0.9697646 ,
        0.05362432,  0.86971524,  0.76320365,  0.558726  ,  0.90960816,
        0.86048992,  0.64749081,  0.07497152,  0.79249777,  0.02458452])

In [17]:
y

array([ 0.65295049,  0.92489308,  0.01254219,  0.10456262,  0.08021775,
        0.83164729,  0.32037566,  0.63287415,  0.60054947,  0.3719682 ,
        0.93099506,  0.01004934,  0.6230401 ,  0.91938009,  0.50833923,
        0.74486386,  0.13728699,  0.11399029,  0.17540258,  0.9697646 ,
        0.05362432,  0.86971524,  0.76320365,  0.558726  ,  0.90960816,
        0.86048992,  0.64749081,  0.07497152,  0.79249777,  0.02458452])

In [18]:
np.dot(x.T, y.T)

11.184984770270821