# 使用Numpy进行科学计算 

**ndarray**可以表示向量、矩阵、张量

In [1]:
from __future__ import print_function, division, unicode_literals, absolute_import
import numpy as np

## 数量积

In [2]:
a = np.random.rand(3)
a

array([ 0.05053049,  0.1125204 ,  0.243122  ])

In [3]:
b = a + 1
b

array([ 1.05053049,  1.1125204 ,  1.243122  ])

## elementwise 计算

In [4]:
a + b

array([ 1.10106099,  1.2250408 ,  1.486244  ])

In [5]:
a - b

array([-1., -1., -1.])

In [6]:
a / b 

array([ 0.04809998,  0.10114008,  0.19557372])

In [7]:
a * b #  也被称为 Hadamard product

array([ 0.05308382,  0.12518124,  0.3022303 ])

Hadamard product: $\bigodot$

## 点积/ dot product

在NN中非常常见的计算操作.

可以用向量内积、向量和矩阵、矩阵和矩阵计算

In [8]:
np.dot(a, b)

0.48049536702334339

In [9]:
a.dot(b)

0.48049536702334339

## 转置

In [10]:
mat = np.random.rand(3, 5)
mat

array([[ 0.46036792,  0.31625266,  0.95772173,  0.16501109,  0.70204813],
       [ 0.06646459,  0.18314373,  0.77050845,  0.44868495,  0.186157  ],
       [ 0.02797905,  0.97111717,  0.64312344,  0.11842192,  0.48562094]])

In [11]:
mat.T

array([[ 0.46036792,  0.06646459,  0.02797905],
       [ 0.31625266,  0.18314373,  0.97111717],
       [ 0.95772173,  0.77050845,  0.64312344],
       [ 0.16501109,  0.44868495,  0.11842192],
       [ 0.70204813,  0.186157  ,  0.48562094]])

In [14]:
np.dot(mat, mat.T)

array([[ 1.74928552,  1.03117971,  1.29640254],
       [ 1.03117971,  0.86761504,  0.81878155],
       [ 1.29640254,  0.81878155,  1.60731059]])

In [15]:
np.matmul(mat, mat.T)

array([[ 1.74928552,  1.03117971,  1.29640254],
       [ 1.03117971,  0.86761504,  0.81878155],
       [ 1.29640254,  0.81878155,  1.60731059]])

如果是一维数组，它的转置还是自己

In [16]:
a = np.random.rand(30)
a

array([ 0.51569225,  0.75154433,  0.00519077,  0.52828216,  0.68768506,
        0.38531156,  0.02282414,  0.83179849,  0.96785048,  0.04574225,
        0.19707435,  0.22742748,  0.99902951,  0.63479594,  0.17643574,
        0.43006655,  0.48204995,  0.48481353,  0.44503683,  0.18505401,
        0.07805468,  0.57435995,  0.16723941,  0.89784298,  0.51123229,
        0.38322125,  0.7307881 ,  0.2254613 ,  0.81921063,  0.90154462])

In [17]:
a.T

array([ 0.51569225,  0.75154433,  0.00519077,  0.52828216,  0.68768506,
        0.38531156,  0.02282414,  0.83179849,  0.96785048,  0.04574225,
        0.19707435,  0.22742748,  0.99902951,  0.63479594,  0.17643574,
        0.43006655,  0.48204995,  0.48481353,  0.44503683,  0.18505401,
        0.07805468,  0.57435995,  0.16723941,  0.89784298,  0.51123229,
        0.38322125,  0.7307881 ,  0.2254613 ,  0.81921063,  0.90154462])

一维数组v的shape是(dim, ), 注意不是(dim, 1)

如果矩阵mat的shape是(dim1, dim), 可以进行np.dot(mat, v)

In [20]:
mat = np.random.rand(30, 1)
mat.shape

(30, 1)

In [22]:
mat.T.shape

(1, 30)