In [22]:
import numpy as np

softmax的特点是如果一个数比较大，则它的概率会趋向于1



而dot product如果和自己相乘，并且维度较高，很容易产生一个较大的数字

In [37]:
def softmax(array):
    array = array - np.max(array)
    return np.exp(array)/np.sum(np.exp(array))

In [24]:
a = np.random.randint(20, 50, 10)

In [25]:
a

array([21, 32, 26, 28, 33, 25, 49, 32, 49, 44])

In [26]:
softmax(a)

array([3.44559161e-13, 2.06301840e-08, 5.11371136e-11, 3.77855001e-10,
       5.60786544e-08, 1.88122928e-11, 4.98321120e-01, 2.06301840e-08,
       4.98321120e-01, 3.35766130e-03])

In [27]:
b = a.copy()
b[1] = 80

In [28]:
softmax(b)

array([2.38026641e-26, 1.00000000e+00, 3.53262857e-24, 2.61027907e-23,
       3.87399763e-21, 1.29958143e-24, 3.44247711e-14, 1.42516408e-21,
       3.44247711e-14, 2.31952283e-16])

In [29]:
b[1] = 60

In [30]:
softmax(b)

array([1.15478371e-17, 9.99966485e-01, 1.71385099e-15, 1.26637411e-14,
       1.87946582e-12, 6.30490545e-16, 1.67011410e-05, 6.91416837e-13,
       1.67011410e-05, 1.12531403e-07])

In [31]:
b[1] = 55

In [32]:
softmax(b)

array([1.70542529e-15, 9.95050414e-01, 2.53107556e-13, 1.87022593e-12,
       2.77566138e-10, 9.31130661e-14, 2.46648338e-03, 1.02110876e-10,
       2.46648338e-03, 1.66190343e-05])

In [38]:
softmax(np.array([1,2]))

array([0.26894142, 0.73105858])

In [39]:
softmax(np.array([1,3]))

array([0.11920292, 0.88079708])

In [40]:
softmax(np.array([1,5]))

array([0.01798621, 0.98201379])

In [41]:
softmax(np.array([1,5, 2, 3]))

array([0.01521943, 0.83095266, 0.0413707 , 0.11245721])

In [43]:
softmax(np.array([1, 5, 2, 3, 4]))

array([0.01165623, 0.63640865, 0.03168492, 0.08612854, 0.23412166])